FROM python:3.9-slim-bullseye AS build

WORKDIR /app
COPY app/* ./
RUN pip3 install --no-cache-dir -r requirements.txt

FROM gcr.io/distroless/python3
COPY --from=build /app/app.py /app/app.py
COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.9/site-packages
EXPOSE 8008
ENTRYPOINT ["python3","app.py"]
