FROM python:3.9-slim-bullseye

WORKDIR /app
COPY --chown=www-data:www-data app/requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY --chown=www-data:www-data app/app.py ./

USER www-data
EXPOSE 8008
ENTRYPOINT ["python3","app.py"]
