FROM ubuntu:22.04

RUN apt-get -y update && \
    apt-get -y install ca-certificates python3-minimal python3-pip && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --chown=www-data:www-data app/requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY --chown=www-data:www-data app/app.py ./

USER www-data
EXPOSE 8008
ENTRYPOINT ["python3","app.py"]
