FROM ubuntu:22.04

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get -y --no-install-recommends install ca-certificates python3-minimal python3-pip python-is-python3 && \
    apt-get -y clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --chown=nobody:nobody app/requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY --chown=nobody:nobody app/app.py ./

USER nobody
EXPOSE 8008
ENTRYPOINT ["python3","app.py"]
